baseURL = "https://fgiorgetti.github.io"
languageCode = "en-us"
title = "Fernando Giorgetti - about me"
theme = "hello-friend-ng"
copyright = "Fernando Giorgetti" # cactus will use title if copyright is not set
disqusShortname = "giorgetti" # Used when comments is enabled. Cactus will use site title if not set
#forcesyncstatic = true
#ignorecache = true

# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "Software engineering"

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Software Engineer and Open source passionate user."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/fgiorgetti" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/fgiorgetti"
    url = "https://github.com/fgiorgetti"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/fernandogiorgetti"
    url = "https://www.linkedin.com/in/fernandogiorgetti"

[languages]
  [languages.en]
    title = "Fernando Giorgetti - about me"
    subtitle = "Software engineering topics"
    keywords = "software"
    copyright = 'Fernando Giorgetti'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "giorgetti.com.br"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

